postgresql_data_dir: "/var/lib/pgsql/17/data/"
postgresql_bin_path: "/usr/pgsql-17/bin"
postgresql_config_path: "/var/lib/pgsql/17/data/"
postgresql_daemon: postgresql-17
postgresql_packages:
- postgresql17
- postgresql17-server
- postgresql17-contrib
postgresql_hba_entries:
- { type: local, database: all, user: postgres, auth_method: peer }
- { type: local, database: all, user: all, auth_method: peer }
- {
    type: host,
    database: all,
    user: all,
    address: '127.0.0.1/32',
    auth_method: "md5"
  }
- {
    type: host,
    database: all,
    user: all,
    address: '::1/128',
    auth_method: "md5"
  }
db_user: "semaphore"
db_password: "password"
db_name: "semaphore"
db_host: "localhost"
